export enum TS_STATUS {
  PENDING='PENDING',
  PROCESSING='PROCESSING',
  L2EXECUTED='L2EXECUTED',
  L2CONFIRMED='L2CONFIRMED',
  L1CONFIRMED='L1CONFIRMED',
  FAILED='FAILED',
  REJECTED='REJECTED'
}
