/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  PoseidonUnit2,
  PoseidonUnit2Interface,
} from "../../../contracts/PoseidonLib.sol/PoseidonUnit2";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[2]",
        name: "input",
        type: "uint256[2]",
      },
    ],
    name: "poseidon",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

export class PoseidonUnit2__factory {
  static readonly abi = _abi;
  static createInterface(): PoseidonUnit2Interface {
    return new utils.Interface(_abi) as PoseidonUnit2Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PoseidonUnit2 {
    return new Contract(address, _abi, signerOrProvider) as PoseidonUnit2;
  }
}
