export enum ORDER_STATUS {
  UNKNOWN='UNKNOWN',
  RUNNING='RUNNING',
  LEND_MATCHED='LEND_MATCHED',
  BORROW_MATCHED='BORROW_MATCHED',
  EXPIRED='EXPIRED',
  CANCELLED='CANCELLED',
  REJECTED='REJECTED'
}