export enum CHANNEL {
  ORDER_CREATED = 'ORDER_CREATED',
  ORDER_VERIFIED = 'ORDER_VERIFIED',
  ORDER_PROCCESSD = 'ORDER_PROCCESSD'
}
export const CHANNELS: CHANNEL[] = [
  CHANNEL.ORDER_CREATED, 
  CHANNEL.ORDER_VERIFIED, 
  CHANNEL.ORDER_PROCCESSD
];